/*
 * generated by Xtext 2.37.0
 */
package formlS.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import formlS.FormlSRuntimeModule;
import formlS.FormlSStandaloneSetup;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class FormlSIdeSetup extends FormlSStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new FormlSRuntimeModule(), new FormlSIdeModule()));
	}
	
}
