/*
 * generated by Xtext 2.37.0
 */
package forml.ide

import com.google.inject.Guice
import forml.FormlRuntimeModule
import forml.FormlStandaloneSetup
import org.eclipse.xtext.util.Modules2

/**
 * Initialization support for running Xtext languages as language servers.
 */
class FormlIdeSetup extends FormlStandaloneSetup {

	override createInjector() {
		Guice.createInjector(Modules2.mixin(new FormlRuntimeModule, new FormlIdeModule))
	}
	
}
