/*
 * generated by Xtext 2.37.0
 */
package formlS;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class FormlSStandaloneSetup extends FormlSStandaloneSetupGenerated {

	public static void doSetup() {
		new FormlSStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
