/*
 * generated by Xtext 2.37.0
 */
package formlS.tests

import com.google.inject.Inject
import formlS.formlS.MockUp
import org.eclipse.xtext.testing.InjectWith
import org.eclipse.xtext.testing.extensions.InjectionExtension
import org.eclipse.xtext.testing.util.ParseHelper
import org.junit.jupiter.api.Assertions
import org.junit.jupiter.api.Test
import org.junit.jupiter.api.^extension.ExtendWith

@ExtendWith(InjectionExtension)
@InjectWith(FormlSInjectorProvider)
class FormlSParsingTest {
	@Inject
	ParseHelper<MockUp> parseHelper
	
	@Test
	def void MockUpTest001() {
		val result = parseHelper.parse('''
			Model TestModel;
		''')
		Assertions.assertNotNull(result)
		val errors = result.eResource.errors
		Assertions.assertTrue(errors.isEmpty, '''Unexpected errors: «errors.join(", ")»''')
	}
	
	@Test
	def void MockUpTest002() {
		val result = parseHelper.parse('''
			"Comment 1"
			Model TestModel;
		''')
		Assertions.assertNotNull(result)
		val errors = result.eResource.errors
		Assertions.assertTrue(errors.isEmpty, '''Unexpected errors: «errors.join(", ")»''')
	}
	
	@Test
	def void MockUpTest003() {
		val result = parseHelper.parse('''
			"Comment 1" "Comment 2"
			"Comment 3"
			Model TestModel;
		''')
		Assertions.assertNotNull(result)
		val errors = result.eResource.errors
		Assertions.assertTrue(errors.isEmpty, '''Unexpected errors: «errors.join(", ")»''')
	}
	
	@Test
	def void MockUpTest004() {
		val result = parseHelper.parse('''
			Model TestModel : Integer a;
		''')
		Assertions.assertNotNull(result)
		val errors = result.eResource.errors
		Assertions.assertTrue(errors.isEmpty, '''Unexpected errors: «errors.join(", ")»''')
	}
	
	@Test
	def void MockUpTest004a() {
		val result = parseHelper.parse('''
			Model TestModel : Integer a is 8;
		''')
		Assertions.assertNotNull(result)
		val errors = result.eResource.errors
		Assertions.assertTrue(errors.isEmpty, '''Unexpected errors: «errors.join(", ")»''')
	}
	
	@Test
	def void MockUpTest004b() {
		val result = parseHelper.parse('''
			Model TestModel : a is 8;
		''')
		Assertions.assertNotNull(result)
		val errors = result.eResource.errors
		Assertions.assertTrue(errors.isEmpty, '''Unexpected errors: «errors.join(", ")»''')
	}
	
	@Test
	def void MockUpTest004c() {
		val result = parseHelper.parse('''
			Model TestModel : Section PartA;
		''')
		Assertions.assertNotNull(result)
		val errors = result.eResource.errors
		Assertions.assertTrue(errors.isEmpty, '''Unexpected errors: «errors.join(", ")»''')
	}
	
	@Test
	def void MockUpTest004d() {
		val result = parseHelper.parse('''
			Model TestModel : Section PartA begin
			end;
		''')
		Assertions.assertNotNull(result)
		val errors = result.eResource.errors
		Assertions.assertTrue(errors.isEmpty, '''Unexpected errors: «errors.join(", ")»''')
	}
	
	@Test
	def void MockUpTest004e() {
		val result = parseHelper.parse('''
			Model TestModel : Section PartA begin
				Integer a;
			end;
		''')
		Assertions.assertNotNull(result)
		val errors = result.eResource.errors
		Assertions.assertTrue(errors.isEmpty, '''Unexpected errors: «errors.join(", ")»''')
	}
	
	@Test
	def void MockUpTest004f() {
		val result = parseHelper.parse('''
			Model TestModel : Section PartA begin
				Integer a is 10;
			end;
		''')
		Assertions.assertNotNull(result)
		val errors = result.eResource.errors
		Assertions.assertTrue(errors.isEmpty, '''Unexpected errors: «errors.join(", ")»''')
	}
	
	@Test
	def void MockUpTest004g() {
		val result = parseHelper.parse('''
			Model TestModel : Section PartA begin
				Integer #a is 10;
			end;
		''')
		Assertions.assertNotNull(result)
		val errors = result.eResource.errors
		Assertions.assertTrue(errors.isEmpty, '''Unexpected errors: «errors.join(", ")»''')
	}
	
	@Test
	def void MockUpTest004h() {
		val result = parseHelper.parse('''
			Model TestModel : Section PartA begin
				@a is 10;
			end;
		''')
		Assertions.assertNotNull(result)
		val errors = result.eResource.errors
		Assertions.assertTrue(errors.isEmpty, '''Unexpected errors: «errors.join(", ")»''')
	}
	
	@Test
	def void MockUpTest004i() {
		val result = parseHelper.parse('''
			Model TestModel : Section PartA begin
				@a is 10;
				Section PartAA;
			end;
		''')
		Assertions.assertNotNull(result)
		val errors = result.eResource.errors
		Assertions.assertTrue(errors.isEmpty, '''Unexpected errors: «errors.join(", ")»''')
	}
	
	@Test
	def void MockUpTest004j() {
		val result = parseHelper.parse('''
			Model TestModel : Section PartA begin
				@a is 10;
				Section PartAA begin
				end PartAA;
			end;
		''')
		Assertions.assertNotNull(result)
		val errors = result.eResource.errors
		Assertions.assertTrue(errors.isEmpty, '''Unexpected errors: «errors.join(", ")»''')
	}
	
	@Test
	def void MockUpTest005() {
		val result = parseHelper.parse('''
			Model TestModel begin
			end;
		''')
		Assertions.assertNotNull(result)
		val errors = result.eResource.errors
		Assertions.assertTrue(errors.isEmpty, '''Unexpected errors: «errors.join(", ")»''')
	}
	
	@Test
	def void MockUpTest006() {
		val result = parseHelper.parse('''
			Model TestModel begin
			end TestModel;
		''')
		Assertions.assertNotNull(result)
		val errors = result.eResource.errors
		Assertions.assertTrue(errors.isEmpty, '''Unexpected errors: «errors.join(", ")»''')
	}
	
	@Test
	def void MockUpTest007() {
		val result = parseHelper.parse('''
			Model TestModel begin
				Integer b is 7; 
			end;
		''')
		Assertions.assertNotNull(result)
		val errors = result.eResource.errors
		Assertions.assertTrue(errors.isEmpty, '''Unexpected errors: «errors.join(", ")»''')
	}
	
	@Test
	def void MockUpTest008() {
		val result = parseHelper.parse('''
			Model TestModel begin
				Integer b is 7; 
				Integer c;
				c is 8;
			end;
		''')
		Assertions.assertNotNull(result)
		val errors = result.eResource.errors
		Assertions.assertTrue(errors.isEmpty, '''Unexpected errors: «errors.join(", ")»''')
	}
	
	@Test
	def void MockUpTest009() {
		val result = parseHelper.parse('''
			Model TestModel begin
				Integer b is 7; 
			end TestModel;
		''')
		Assertions.assertNotNull(result)
		val errors = result.eResource.errors
		Assertions.assertTrue(errors.isEmpty, '''Unexpected errors: «errors.join(", ")»''')
	}
	
	@Test
	def void MockUpTest010() {
		val result = parseHelper.parse('''
			Model TestModel begin
				Integer b is 7; 
				Integer c is 8;
			end TestModel;
		''')
		Assertions.assertNotNull(result)
		val errors = result.eResource.errors
		Assertions.assertTrue(errors.isEmpty, '''Unexpected errors: «errors.join(", ")»''')
	}
	
	@Test
	def void MockUpTest011() {
		val result = parseHelper.parse('''
			Model TestModel extends Standard begin
				Integer b is 7; 
				Integer c is 8;
			end TestModel;
		''')
		Assertions.assertNotNull(result)
		val errors = result.eResource.errors
		Assertions.assertTrue(errors.isEmpty, '''Unexpected errors: «errors.join(", ")»''')
	}
	
	@Test
	def void MockUpTest012() {
		val result = parseHelper.parse('''
			Model TestModel extends Standard, Other begin
				Integer b is 7; 
				c is 8;
			end TestModel;
		''')
		Assertions.assertNotNull(result)
		val errors = result.eResource.errors
		Assertions.assertTrue(errors.isEmpty, '''Unexpected errors: «errors.join(", ")»''')
	}
	
	@Test
	def void MockUpTest013() {
		val result = parseHelper.parse('''
			Model TestModel 'comment' 'comment'
				extends Standard 
			begin
				b is 7; 
				c is 8;
			end TestModel;
		''')
		Assertions.assertNotNull(result)
		val errors = result.eResource.errors
		Assertions.assertTrue(errors.isEmpty, '''Unexpected errors: «errors.join(", ")»''')
	}
	
	@Test
	def void MockUpTest014() {
		val result = parseHelper.parse('''
			Model TestModel 'comment' 'comment'
				extends Standard 
			'comment' 'comment'	
			begin
				b is 7; 
				c is 8;
			end TestModel;
		''')
		Assertions.assertNotNull(result)
		val errors = result.eResource.errors
		Assertions.assertTrue(errors.isEmpty, '''Unexpected errors: «errors.join(", ")»''')
	}
	
	@Test
	def void MockUpTest015() {
		val result = parseHelper.parse('''
			Model TestModel extends Standard, Other begin
				b is 7; 
				Integer ?c;
			end TestModel;
			d is 5;
		''')
		Assertions.assertNotNull(result)
		val errors = result.eResource.errors
		Assertions.assertTrue(errors.isEmpty, '''Unexpected errors: «errors.join(", ")»''')
	}
	
	@Test
	def void MockUpTest016() {
		val result = parseHelper.parse('''
			Model TestModel extends Standard, Other begin
				b is 7; 
				!c is 8;
			end TestModel;
			d is 5;
			Integer e;
		''')
		Assertions.assertNotNull(result)
		val errors = result.eResource.errors
		Assertions.assertTrue(errors.isEmpty, '''Unexpected errors: «errors.join(", ")»''')
	}
	
	@Test
	def void MockUpTest017() {
		val result = parseHelper.parse('''
			Model TestModel 'comment' 'comment'
				extends Standard 
			'comment' 'comment'	
			begin
				b is 7; 
				~c is 8;
			end TestModel;
			Model Other 'comment' 'comment'
				extends Standard 
				'comment' 'comment'	
			begin
				b is 7; 
				Integer c is 8;
			end Other;
		''')
		Assertions.assertNotNull(result)
		val errors = result.eResource.errors
		Assertions.assertTrue(errors.isEmpty, '''Unexpected errors: «errors.join(", ")»''')
	}
	
	@Test
	def void MockUpTest018() {
		val result = parseHelper.parse('''
			Model TestModel 'comment' 'comment'
				extends Standard 
			'comment' 'comment'	
			begin
				b is 7; 
				c is 8;
			end TestModel;
			d is 5;
			Integer e;
			Model Other 'comment' 'comment'
				extends Standard 
				'comment' 'comment'	
			begin
				!b is 7; 
				Integer c;
			end Other;
		''')
		Assertions.assertNotNull(result)
		val errors = result.eResource.errors
		Assertions.assertTrue(errors.isEmpty, '''Unexpected errors: «errors.join(", ")»''')
	}
	
	@Test
	def void MockUpTest019() {
		val result = parseHelper.parse('''
			Model TestModel 'comment' 'comment'
				extends Standard 
			'comment' 'comment'	
			begin
				b is 7; 
				c is 8;
			end TestModel;
			d is 5;
			Integer #e;
			Model Other 'comment' 'comment'
				extends Standard 
				'comment' 'comment'	
			begin
				b is 7; 
				Integer c;
			end Other;
			@c is 10;
 		''')
		Assertions.assertNotNull(result)
		val errors = result.eResource.errors
		Assertions.assertTrue(errors.isEmpty, '''Unexpected errors: «errors.join(", ")»''')
	}
}
