/*
 * generated by Xtext 2.37.0
 */
package forml.ui.contentassist


/**
 * See https://www.eclipse.org/Xtext/documentation/310_eclipse_support.html#content-assist
 * on how to customize the content assistant.
 */
class FormlProposalProvider extends AbstractFormlProposalProvider {
}
