/*
 * generated by Xtext 2.37.0
 */
package forml


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class FormlStandaloneSetup extends FormlStandaloneSetupGenerated {

	def static void doSetup() {
		new FormlStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
