/*
 * generated by Xtext 2.37.0
 */
package forml


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class FormlRuntimeModule extends AbstractFormlRuntimeModule {
}
