/*
 * generated by Xtext 2.37.0
 */
package formlS.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class FormlSUiModule extends AbstractFormlSUiModule {

	public FormlSUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
